OK_FORMAT = True

test = {   'name': 'q1.2.2',
    'points': 2,
    'suites': [   {   'cases': [   {'code': '>>> isinstance(X_122, np.ndarray)\nTrue', 'failure_message': 'Answer is not a numpy array.', 'hidden': False, 'locked': False, 'points': 0},
                                   {'code': '>>> X_122.shape == (3, 3)\nTrue', 'failure_message': 'Answer does not have the correct shape.', 'hidden': False, 'locked': False, 'points': 0},
                                   {   'code': '>>> R_122 = X_122[:2, :2]\n>>> np.allclose(R_122.T @ R_122, np.eye(2), atol=0.001) and np.allclose(R_122 @ R_122.T, np.eye(2), atol=0.001)\nTrue',
                                       'failure_message': 'Answer does not contain a rotation matrix in the top left corner (R^TR = I, RR^T = I).',
                                       'hidden': False,
                                       'locked': False,
                                       'points': 0},
                                   {   'code': '>>> R_122 = X_122[:2, :2]\n>>> np.isclose(np.linalg.det(R_122), 1.0, atol=0.001).item()\nTrue',
                                       'failure_message': 'Answer does not contain a rotation matrix in the top left corner (det(R) = +1).',
                                       'hidden': False,
                                       'locked': False,
                                       'points': 0},
                                   {   'code': '>>> np.allclose(X_122[2, :], np.array([0, 0, 1]), atol=0.001)\nTrue',
                                       'failure_message': 'Answer does not contain a bottom row that is [0, 0, 1].',
                                       'hidden': False,
                                       'locked': False,
                                       'points': 0}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
