OK_FORMAT = True

test = {   'name': 'q1.3.5',
    'points': 2,
    'suites': [   {   'cases': [   {'code': '>>> isinstance(R_1351, np.ndarray)\nTrue', 'failure_message': 'R_1351 is not a numpy array.', 'hidden': False, 'locked': False, 'points': 0},
                                   {'code': '>>> isinstance(R_1352, np.ndarray)\nTrue', 'failure_message': 'R_1352 is not a numpy array.', 'hidden': False, 'locked': False, 'points': 0},
                                   {'code': '>>> R_1351.shape == (3, 3)\nTrue', 'failure_message': 'R_1351 does not have the correct shape.', 'hidden': False, 'locked': False, 'points': 0},
                                   {'code': '>>> R_1352.shape == (3, 3)\nTrue', 'failure_message': 'R_1352 does not have the correct shape.', 'hidden': False, 'locked': False, 'points': 0},
                                   {   'code': '>>> np.allclose(R_1351.T @ R_1351, np.eye(3), atol=0.001) and np.allclose(R_1351 @ R_1351.T, np.eye(3), atol=0.001)\nTrue',
                                       'failure_message': 'R_1351 is not a rotation matrix (R^TR = I, RR^T = I).',
                                       'hidden': False,
                                       'locked': False,
                                       'points': 0},
                                   {   'code': '>>> np.allclose(R_1352.T @ R_1352, np.eye(3), atol=0.001) and np.allclose(R_1352 @ R_1352.T, np.eye(3), atol=0.001)\nTrue',
                                       'failure_message': 'R_1352 is not a rotation matrix (R^TR = I, RR^T = I).',
                                       'hidden': False,
                                       'locked': False,
                                       'points': 0},
                                   {   'code': '>>> np.isclose(np.linalg.det(R_1351), 1.0, atol=0.001).item()\nTrue',
                                       'failure_message': 'R_1351 is not a rotation matrix (det(R) =+1).',
                                       'hidden': False,
                                       'locked': False,
                                       'points': 0},
                                   {   'code': '>>> np.isclose(np.linalg.det(R_1352), 1.0, atol=0.001).item()\nTrue',
                                       'failure_message': 'R_1352 is not a rotation matrix (det(R) = +1).',
                                       'hidden': False,
                                       'locked': False,
                                       'points': 0}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
