OK_FORMAT = True

test = {   'name': 'q1.3.6',
    'points': 2,
    'suites': [   {   'cases': [   {'code': '>>> isinstance(R_1361, np.ndarray)\nTrue', 'failure_message': 'R_1361 is not a numpy array.', 'hidden': False, 'locked': False, 'points': 0},
                                   {'code': '>>> isinstance(R_1362, np.ndarray)\nTrue', 'failure_message': 'R_1362 is not a numpy array.', 'hidden': False, 'locked': False, 'points': 0},
                                   {'code': '>>> R_1361.shape == (3, 3)\nTrue', 'failure_message': 'R_1361 does not have the correct shape.', 'hidden': False, 'locked': False, 'points': 0},
                                   {'code': '>>> R_1362.shape == (3, 3)\nTrue', 'failure_message': 'R_1362 does not have the correct shape.', 'hidden': False, 'locked': False, 'points': 0},
                                   {   'code': '>>> np.allclose(R_1361.T @ R_1361, np.eye(3), atol=0.001) and np.allclose(R_1361 @ R_1361.T, np.eye(3), atol=0.001)\nTrue',
                                       'failure_message': 'R_1361 is not a rotation matrix (R^TR = I, RR^T = I).',
                                       'hidden': False,
                                       'locked': False,
                                       'points': 0},
                                   {   'code': '>>> np.allclose(R_1362.T @ R_1362, np.eye(3), atol=0.001) and np.allclose(R_1362 @ R_1362.T, np.eye(3), atol=0.001)\nTrue',
                                       'failure_message': 'R_1362 is not a rotation matrix (R^TR = I, RR^T = I).',
                                       'hidden': False,
                                       'locked': False,
                                       'points': 0},
                                   {   'code': '>>> np.isclose(np.linalg.det(R_1361), 1.0, atol=0.001).item()\nTrue',
                                       'failure_message': 'R_1361 is not a rotation matrix (det(R) =+1).',
                                       'hidden': False,
                                       'locked': False,
                                       'points': 0},
                                   {   'code': '>>> np.isclose(np.linalg.det(R_1362), 1.0, atol=0.001).item()\nTrue',
                                       'failure_message': 'R_1362 is not a rotation matrix (det(R) = +1).',
                                       'hidden': False,
                                       'locked': False,
                                       'points': 0},
                                   {   'code': '>>> not np.allclose(R_1361, np.eye(3), atol=0.001)\nTrue',
                                       'failure_message': 'R_1361 is the identity rotation.',
                                       'hidden': False,
                                       'locked': False,
                                       'points': 0},
                                   {   'code': '>>> not np.allclose(R_1362, np.eye(3), atol=0.001)\nTrue',
                                       'failure_message': 'R_1362 is the identity rotation.',
                                       'hidden': False,
                                       'locked': False,
                                       'points': 0},
                                   {   'code': '>>> not np.allclose(R_1361, R_1362, atol=0.001)\nTrue',
                                       'failure_message': 'R_1361 and R_1362 are not distinct.',
                                       'hidden': False,
                                       'locked': False,
                                       'points': 0}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
