OK_FORMAT = True

test = {   'name': 'q3.1',
    'points': 5,
    'suites': [   {   'cases': [   {'code': '>>> isinstance(R_G_31, np.ndarray)\nTrue', 'failure_message': 'Answer is not a numpy array.', 'hidden': False, 'locked': False, 'points': 0},
                                   {'code': '>>> R_G_31.shape == (3, 3)\nTrue', 'failure_message': 'Answer does not have the correct shape.', 'hidden': False, 'locked': False, 'points': 0},
                                   {   'code': '>>> np.allclose(R_G_31.T @ R_G_31, np.eye(3), atol=0.001) and np.allclose(R_G_31 @ R_G_31.T, np.eye(3), atol=0.001)\nTrue',
                                       'failure_message': 'Answer is not a rotation matrix (R^TR = I, RR^T = I).',
                                       'hidden': False,
                                       'locked': False,
                                       'points': 0},
                                   {   'code': '>>> np.isclose(np.linalg.det(R_G_31), 1.0, atol=0.001).item()\nTrue',
                                       'failure_message': 'Answer is not a rotation matrix (det(R) =+1).',
                                       'hidden': False,
                                       'locked': False,
                                       'points': 0}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
