OK_FORMAT = True

test = {   'name': 'q3.3.2',
    'points': 3,
    'suites': [   {   'cases': [   {'code': '>>> isinstance(p_Gpick_332, np.ndarray)\nTrue', 'failure_message': 'p_Gpick_332 is not a numpy array.', 'hidden': False, 'locked': False, 'points': 0},
                                   {'code': '>>> p_Gpick_332.shape == (3,)\nTrue', 'failure_message': 'p_Gpick_332 does not have the correct shape.', 'hidden': False, 'locked': False, 'points': 0},
                                   {   'code': '>>> isinstance(quat_Gpick_332, np.ndarray)\nTrue',
                                       'failure_message': 'quat_Gpick_332 is not a numpy array).',
                                       'hidden': False,
                                       'locked': False,
                                       'points': 0},
                                   {   'code': '>>> quat_Gpick_332.shape == (4,)\nTrue',
                                       'failure_message': 'quat_Gpick_332 does not have the correct shape.',
                                       'hidden': False,
                                       'locked': False,
                                       'points': 0},
                                   {   'code': '>>> np.isclose(np.sum(quat_Gpick_332 ** 2), 1.0, atol=0.001).item()\nTrue',
                                       'failure_message': 'quat_Gpick_332 is not a unit quaternion (q_0^2 q_1^2 + q_2^2 + q_3^2 = 1).',
                                       'hidden': False,
                                       'locked': False,
                                       'points': 0}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
